"""username added

Revision ID: 12492bf39648
Revises: 47b9517920d9
Create Date: 2022-12-16 00:31:49.971945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12492bf39648'
down_revision = '47b9517920d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=25), nullable=False))
        batch_op.create_unique_constraint(None, ['user_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
