"""username added

Revision ID: 9578d24725a9
Revises: 12492bf39648
Create Date: 2022-12-16 00:38:01.479779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9578d24725a9'
down_revision = '12492bf39648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=25), nullable=False))
        batch_op.drop_index('user_name')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', mysql.VARCHAR(length=25), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('user_name', ['user_name'], unique=False)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
